name: quora_challenge_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - spacy
  - joblib
  - matplotlib
  - pip
  - pip:
      - python-Levenshtein